version: '3.1'
services:
  rsm-msba-spark:
    image: "vnijs/rsm-msba-spark"
    environment:
      SHELL: bin/bash
      PYTHONUSERBASE: /home/jovyan/.rsm-msba
      JUPYTER_PATH: /home/jovyan/.rsm-msba/share/jupyter
      JUPYTER_RUNTIME_DIR: /home/jovyan/.rsm-msba/share/jupyter/runtime
      JUPYTER_CONFIG_DIR: /home/jovyan/.rsm-msba/jupyter
      RPASSWORD: rstudio
      JPASSWORD: jupyter
    ports:
      - 8080:8080
      - 8787:8787
      - 8989:8989
    volumes:
      - ~:/home/jovyan

  postgres:
    image: postgres:10.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
    volumes:
       - pg_data:/var/lib/postgresql/data:Z

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
    restart: always
    volumes:
       - ~/postgresql/pgadmin:/var/lib/pgadmin

volumes:
  pg_data:
    external: true
