FROM vnijs/radiant:1.1.1

MAINTAINER Vincent Nijs "radiant@rady.ucsd.edu"

ARG DOCKERHUB_VERSION_UPDATE
ENV DOCKERHUB_VERSION=${DOCKERHUB_VERSION_UPDATE}

## update R-packages
RUN R -e 'radiant.update::radiant.update()'

## update radiant to development version
RUN R -e 'remotes::install_github("radiant-rstats/radiant.data", upgrade = "never")' \
  -e 'remotes::install_github("radiant-rstats/radiant.basics", upgrade = "never")' \
  -e 'remotes::install_github("radiant-rstats/radiant.design", upgrade = "never")' \
  -e 'remotes::install_github("radiant-rstats/radiant.model", upgrade = "never")' \
  -e 'remotes::install_github("radiant-rstats/radiant.multivariate", upgrade = "never")'

## packages in development
RUN R -e 'remotes::install_github("PMassicotte/gtrendsR@da29cf4e427b6bf33d5925ce82596d9c33f9656c", upgrade = "never")' \
  -e 'remotes::install_github("thomasp85/gganimate")' \
  -e 'remotes::install_github("tidymodels/tidymodels")'

## install lightGBM
#RUN git clone --recursive https://github.com/Microsoft/LightGBM \
#  && cd LightGBM \
#  && Rscript build_r.R \
#  && cd .. \
#  && rm -rf LightGBM

## path for local install of python packages from Rstudio or Jupyter Lab
ARG PYBASE=/home/${NB_USER}/.rsm-msba
ENV PYBASE=${PYBASE}
RUN echo "PYTHONUSERBASE=${PYBASE}" >> /etc/R/Renviron.site \
  && echo "WORKON_HOME=${PYBASE}" >> /etc/R/Renviron.site

EXPOSE 8080 8787

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
