name: rsm-jupyter docker ci

on:
  push:
    branches:
      - 'master'
    paths:
      - 'rsm-jupyter/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Cleanup tools
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      -
        name: Prepare tags
        id: tag_prep
        run: |
          TAGS="latest,$(git rev-parse --short '$GITHUB_SHA')"
          if [[ $(head -n 1 rsm-jupyter/Dockerfile) == "# __version__"* ]]; then
            TAGS="latest,$(head -n 1 rsm-jupyter/Dockerfile | sed 's/^# __version__ //')"
          fi
          echo ::set-output name=tags::${TAGS}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          image: ${{ secrets.DOCKERHUB_USERNAME }}/rsm-jupyter
          file: ./rsm-jupyter/Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.tag_prep.outputs.tags }}
